VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Client"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Dim cl_id       As String
Dim cl_lName    As String
Dim cl_fName    As String
Dim cl_mi       As String
Dim cl_dob      As String
Dim cl_nat      As String
Dim cl_sex      As String
Dim cl_add1     As String
Dim cl_add2     As String
Dim cl_add3     As String
Dim cl_country  As String
Dim cl_state    As String
Dim cl_city     As String
Dim cl_phone    As String
Dim cl_altPhone As String
Dim cl_fax      As String
Dim cl_email    As String
Dim cl_addInfo  As String


